config/routes.rb
Teamplatform::Application.routes.draw do
  get 'tp/index'
  get 'tp/welcome'
  root :to => 'tp#welcome'
  match 'callback' => 'tp#callback'
  match 'authorize' => 'tp#authorize'
  match 'logout' => 'tp#logout'
  match 'create_workspace' => 'tp#create_workspace'
  match 'delete_workspace' => 'tp#delete_workspace'
  match 'update_workspace' => 'tp#update_workspace'
  match 'edit_workspace' => 'tp#edit_workspace'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tp_controller.rb
require 'oauth2'
require 'json'

CLIENT_ID = TP_CONFIG['client_id']
CLIENT_SECRET = TP_CONFIG['client_secret'] 
REDIRECT_URI = "http://localhost:3000/callback/"


class TpController < ApplicationController

before_filter :auth_user, :only => :index

OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

  # Declare client to be used in handshake with TeamPlatform
  def client
    OAuth2::Client.new(CLIENT_ID, CLIENT_SECRET, {
      :authorize_url => 'https://teamplatform.com/api/v1/oauth/authorize',
      :token_url => 'https://teamplatform.com/api/v1/oauth/access_token',
      :token_method => :post })
  end
 
  # Check if session has been set to access_token, otherwise, send for authorization
  def auth_user
    return redirect_to(:action => 'authorize') unless session[:access_token]
  end 
  
  # Send authorization request 
  def authorize
      redirect_to client.auth_code.authorize_url(:redirect_uri => REDIRECT_URI)
  end

  # Receive callback code and request access token
  def callback
    access_token = client.auth_code.get_token(params[:code], :redirect_uri => REDIRECT_URI)
    session[:access_token] = access_token.token
    redirect_to tp_index_url 
  end
  
  # Log user out
  def logout
    session[:access_token] = nil
    redirect_to tp_welcome_url
  end
  
  # Fetch url and parse JSON response
  def get_collection(path)
    uri = URI.parse(path)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = http.get(uri.request_uri)
    JSON.parse(response.body)
  end
  
  # Post JSON details to specified url based on method
  def post_collection(type, path, data)
    uri = URI.parse(path)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    if type == 'create' then
      req = Net::HTTP::Post.new(uri.request_uri)
      req.set_form_data(data)
    elsif type == 'delete' then
      req = Net::HTTP::Delete.new(uri.request_uri)
    elsif type == 'update' then    
      req = Net::HTTP::Put.new(uri.request_uri)
      req.set_form_data(data)
    end
    response = http.request(req)
  end
  
  # Get account information
  def index
   @atoken = session[:access_token]
   @profile = get_collection("https://teamplatform.com/api/v1/profile?access_token="+@atoken)
   @workspaces = get_collection("https://teamplatform.com/api/v1/workspaces?access_token="+@atoken)
   @files = get_collection("https://teamplatform.com/api/v1/files?access_token="+@atoken)
   @pages = get_collection("https://teamplatform.com/api/v1/pages?access_token="+@atoken)
   @comments = get_collection("https://teamplatform.com/api/v1/comments?access_token="+@atoken)
   @tasks = get_collection("https://teamplatform.com/api/v1/tasks?access_token="+@atoken)
  end
  
 
  # Create new workspace
  def create_workspace
    path = 'https://teamplatform.com/api/v1/workspaces?access_token='+ session[:access_token]
    data = {'title' => params[:title], 'description' => params[:description]}
    post = post_collection('create',path, data)
    redirect_to tp_index_path
  end
  
  # Delete workspace
  def delete_workspace
    if params[:purge] == nil then
      path = "https://teamplatform.com/api/v1/workspaces/#{params[:id]}?access_token="+ session[:access_token]
    elsif params[:purge] == 'true' then
      path = "https://teamplatform.com/api/v1/workspaces/#{params[:id]}?access_token="+ session[:access_token] + '&purge=true'
    end
    post = post_collection('delete', path, '') 
    redirect_to tp_index_path
  end
  
  # Update workspace
  def update_workspace
    path = "https://teamplatform.com/api/v1/workspaces/#{params[:id]}?access_token="+ session[:access_token]
    data = {'title' => params[:title], 'description' => params[:description], 'status' => 'active'}
    post = post_collection('update', path, data)
    redirect_to tp_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teamplatform</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tp/_createworkspace.html.erb
<%= form_tag({:controller => :tp, :action => :create_workspace}, :method => "post")  do %>

  <div class="field">
    <%= text_field_tag  :title, params[:title], :placeholder => 'Workspace name' %>
	<%= text_field_tag  :description, params[:description], :placeholder => 'Description' %>
  </div>
  <div class="actions">
    <%= submit_tag "Create Workspace" %>
  </div>
<% end %>

app/views/tp/edit_workspace.html.erb
<div id='section'><h2>Edit Workspace</h2>
<%= form_tag({:controller => :tp, :action => :update_workspace}, :method => "post")  do %>
    <%= text_field_tag  :title, params[:title], :placeholder => 'Workspace name' %>
	<%= text_field_tag  :description, params[:description], :placeholder => 'Description' %>
	<%= hidden_field_tag :id, params[:id] %>
    <%= submit_tag "Update Workspace" %>
<% end %>
</div>

app/views/tp/index.html.erb
<div id ='section'><h1>TeamPlatform API</h1></div>
<br />
<div id='section'><h2>Profile</h2>
<p><img id= 'tpprofile' src = "<%= @profile['picture'] %>" height ="150" width = "150" align = "left"></p>
<p>Name: <%= @profile['name']%>  |  <%= link_to "Logout", logout_path %></p>
<p>ID: <%= @profile['id']%></p>
<p>Email: <%= @profile['email']%></p>
<p>Team Name: <%= @profile['team_name']%></p> 
<p>Team ID: <%= @profile['team_id']%></p>
<p>Current Access Token: <%=@atoken %></p>
</div>
<br />

<% wcount = 0 
	@workspaces.each do |w| 
		if w['deleted_at'] == nil then 
			wcount = wcount +1 
		end
	end%>
	
<div id='section'><h2>Workspaces: <%= wcount %></h2>
<% @workspaces.each do |w|
if w['is_template'] == false and w['deleted_at'] == nil then %>
	<li><%= w['title']%> - <%= w['description']%> | <%= link_to "Edit", 
	edit_workspace_path(:title => w['title'], :description => w['description'], :id => w['id']) %> | 
	<%= link_to "Delete", delete_workspace_path(:id => w['id']), 
	:data => {:confirm => 'Delete this workspace?'} %></li>
<% elsif w['is_template'] == true and w['deleted_at'] == nil then  %>
	<li><%= w['title']%> (template) | <%= link_to "Edit", 
	edit_workspace_path(:title => w['title'], :description => w['description'], :id => w['id']) %> | 
	<%= link_to "Delete", delete_workspace_path(:id => w['id']), 
	:data => {:confirm => 'Delete this workspace?'} %></li>
<% end %>
<% end %>

<p></p>
<%= render 'createworkspace' %>

<h2>Workspaces in trash</h2>
<% @workspaces.each do |w| 
if not w['deleted_at'] == nil then %>
<li><%= w['title']%> (trash) | <%= link_to "Purge", delete_workspace_path(:id => w['id'], :purge => 'true'),
:data => {:confirm => "Purge this workspace permanently?"}%></li>
<% end %>
<% end %>
</div>
<br/>

<div id='section'><h2>Account Stats:</h2>
<li># Workspaces: <%= @workspaces.count%></li>
<li># Pages: <%= @pages.count%></li>
<li># Files: <%= @files.count%></li>
<li># Comments: <%= @comments.count%></li>
<li># Tasks: <%= @tasks.count%></li>
</div>

app/views/tp/welcome.html.erb
<div id ='section'><center><h1>TeamPlatform API - RoR Client</h1></center></div> 
<br/>
<br/>
<div id = 'section'><center><p>Click to Authenticate</p>
	<p><%= link_to image_tag("tp-logo.png", :width => "300", :class =>"tplogin"), tp_index_path%></center></p><div>